-- Adempiere Seed Data for Migration Testing
-- Populates core reference tables with minimal data to exercise
-- the data migration pipeline (FK ordering, COPY mode, row verification).
--
-- Tables populated (in FK dependency order):
--   AD_CLIENT (2 rows)     - Top-level tenant
--   AD_ORG (3 rows)        - Organizations within client
--   AD_USER (5 rows)       - System users
--   AD_ROLE (4 rows)       - Security roles
--   AD_LANGUAGE (3 rows)   - Supported languages
--   AD_ELEMENT (10 rows)   - Data dictionary elements
--   AD_TABLE (10 rows)     - Table metadata
--   C_CURRENCY (5 rows)    - Currencies
--   C_COUNTRY (10 rows)    - Countries
--   C_REGION (5 rows)      - Regions/states
--   C_BPARTNER (10 rows)   - Business partners
--   M_PRODUCT (10 rows)    - Products
--   C_ORDER (5 rows)       - Sales orders
--   C_ORDERLINE (15 rows)  - Order line items

-- ============================================================
-- AD_CLIENT: Top-level tenants
-- ============================================================
INSERT INTO AD_CLIENT (AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY, UPDATED, UPDATEDBY,
    VALUE, NAME, DESCRIPTION, SMTPHOST, REQUESTEMAIL, REQUESTUSER, REQUESTUSERPW,
    REQUESTFOLDER, AD_LANGUAGE, WEBINFO, WEBPARAM1, WEBPARAM2, WEBPARAM3,
    WEBPARAM4, WEBPARAM5, WEBPARAM6, WEBDIR, DOCUMENTDIR, AUTOARCHIVE)
VALUES (0, 0, SYSDATE, 0, SYSDATE, 0,
    'SYSTEM', 'System', 'System Client', 'localhost', 'admin@test.com', 'admin', 'admin',
    'INBOX', 'en_US', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'N');

INSERT INTO AD_CLIENT (AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY, UPDATED, UPDATEDBY,
    VALUE, NAME, DESCRIPTION, SMTPHOST, REQUESTEMAIL, REQUESTUSER, REQUESTUSERPW,
    REQUESTFOLDER, AD_LANGUAGE, WEBINFO, WEBPARAM1, WEBPARAM2, WEBPARAM3,
    WEBPARAM4, WEBPARAM5, WEBPARAM6, WEBDIR, DOCUMENTDIR, AUTOARCHIVE)
VALUES (11, 0, SYSDATE, 0, SYSDATE, 0,
    'GARDEN', 'GardenWorld', 'GardenWorld Demo Client', 'localhost', 'info@garden.com', 'garden', 'garden',
    'INBOX', 'en_US', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'N');

-- ============================================================
-- AD_ORG: Organizations
-- ============================================================
INSERT INTO AD_ORG (AD_ORG_ID, AD_CLIENT_ID, CREATED, CREATEDBY, UPDATED, UPDATEDBY,
    VALUE, NAME, DESCRIPTION)
VALUES (0, 0, SYSDATE, 0, SYSDATE, 0, '*', '*', 'All Organizations');

INSERT INTO AD_ORG (AD_ORG_ID, AD_CLIENT_ID, CREATED, CREATEDBY, UPDATED, UPDATEDBY,
    VALUE, NAME, DESCRIPTION)
VALUES (11, 11, SYSDATE, 0, SYSDATE, 0, 'HQ', 'HQ', 'GardenWorld Headquarters');

INSERT INTO AD_ORG (AD_ORG_ID, AD_CLIENT_ID, CREATED, CREATEDBY, UPDATED, UPDATEDBY,
    VALUE, NAME, DESCRIPTION)
VALUES (12, 11, SYSDATE, 0, SYSDATE, 0, 'STORE', 'Store', 'GardenWorld Retail Store');

-- ============================================================
-- AD_LANGUAGE: Supported languages
-- ============================================================
INSERT INTO AD_LANGUAGE (AD_LANGUAGE, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, LANGUAGEISO, COUNTRYCODE, ISBASELANGUAGE, ISSYSTEMLANGUAGE)
VALUES ('en_US', 0, 0, SYSDATE, 0, SYSDATE, 0, 'English (USA)', 'en', 'US', 'Y', 'Y');

INSERT INTO AD_LANGUAGE (AD_LANGUAGE, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, LANGUAGEISO, COUNTRYCODE, ISBASELANGUAGE, ISSYSTEMLANGUAGE)
VALUES ('de_DE', 0, 0, SYSDATE, 0, SYSDATE, 0, 'German (Germany)', 'de', 'DE', 'N', 'Y');

INSERT INTO AD_LANGUAGE (AD_LANGUAGE, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, LANGUAGEISO, COUNTRYCODE, ISBASELANGUAGE, ISSYSTEMLANGUAGE)
VALUES ('es_ES', 0, 0, SYSDATE, 0, SYSDATE, 0, 'Spanish (Spain)', 'es', 'ES', 'N', 'N');

-- ============================================================
-- AD_USER: System users
-- ============================================================
INSERT INTO AD_USER (AD_USER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, PASSWORD, EMAIL)
VALUES (0, 0, 0, SYSDATE, 0, SYSDATE, 0, 'SuperUser', 'System Administrator', 'System', 'admin@system.com');

INSERT INTO AD_USER (AD_USER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, PASSWORD, EMAIL)
VALUES (100, 11, 0, SYSDATE, 0, SYSDATE, 0, 'GardenAdmin', 'GardenWorld Admin', 'GardenAdmin', 'admin@garden.com');

INSERT INTO AD_USER (AD_USER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, PASSWORD, EMAIL)
VALUES (101, 11, 11, SYSDATE, 0, SYSDATE, 0, 'GardenUser', 'GardenWorld User', 'GardenUser', 'user@garden.com');

INSERT INTO AD_USER (AD_USER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, PASSWORD, EMAIL)
VALUES (102, 11, 11, SYSDATE, 0, SYSDATE, 0, 'Sales Rep', 'Sales Representative', 'SalesRep', 'sales@garden.com');

INSERT INTO AD_USER (AD_USER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, PASSWORD, EMAIL)
VALUES (103, 11, 12, SYSDATE, 0, SYSDATE, 0, 'Store Clerk', 'Retail Store Clerk', 'StoreClerk', 'store@garden.com');

-- ============================================================
-- AD_ROLE: Security roles
-- ============================================================
INSERT INTO AD_ROLE (AD_ROLE_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, USERLEVEL)
VALUES (0, 0, 0, SYSDATE, 0, SYSDATE, 0, 'System Administrator', 'Full system access', 'S  ');

INSERT INTO AD_ROLE (AD_ROLE_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, USERLEVEL)
VALUES (102, 11, 0, SYSDATE, 0, SYSDATE, 0, 'GardenWorld Admin', 'Client administrator', ' CO');

INSERT INTO AD_ROLE (AD_ROLE_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, USERLEVEL)
VALUES (103, 11, 0, SYSDATE, 0, SYSDATE, 0, 'Sales', 'Sales role', '  O');

INSERT INTO AD_ROLE (AD_ROLE_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, USERLEVEL)
VALUES (104, 11, 0, SYSDATE, 0, SYSDATE, 0, 'Store Manager', 'Store management role', '  O');

-- ============================================================
-- C_CURRENCY: Currencies
-- ============================================================
INSERT INTO C_CURRENCY (C_CURRENCY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, ISO_CODE, CURSYMBOL, DESCRIPTION, STDPRECISION, COSTINGPRECISION)
VALUES (100, 0, 0, SYSDATE, 0, SYSDATE, 0, 'USD', '$', 'US Dollar', 2, 4);

INSERT INTO C_CURRENCY (C_CURRENCY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, ISO_CODE, CURSYMBOL, DESCRIPTION, STDPRECISION, COSTINGPRECISION)
VALUES (102, 0, 0, SYSDATE, 0, SYSDATE, 0, 'EUR', '!', 'Euro', 2, 4);

INSERT INTO C_CURRENCY (C_CURRENCY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, ISO_CODE, CURSYMBOL, DESCRIPTION, STDPRECISION, COSTINGPRECISION)
VALUES (103, 0, 0, SYSDATE, 0, SYSDATE, 0, 'GBP', '#', 'British Pound', 2, 4);

INSERT INTO C_CURRENCY (C_CURRENCY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, ISO_CODE, CURSYMBOL, DESCRIPTION, STDPRECISION, COSTINGPRECISION)
VALUES (104, 0, 0, SYSDATE, 0, SYSDATE, 0, 'JPY', 'Y', 'Japanese Yen', 0, 2);

INSERT INTO C_CURRENCY (C_CURRENCY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, ISO_CODE, CURSYMBOL, DESCRIPTION, STDPRECISION, COSTINGPRECISION)
VALUES (105, 0, 0, SYSDATE, 0, SYSDATE, 0, 'CAD', 'C$', 'Canadian Dollar', 2, 4);

-- ============================================================
-- C_COUNTRY: Countries
-- ============================================================
INSERT INTO C_COUNTRY (C_COUNTRY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, COUNTRYCODE, C_CURRENCY_ID, HASREGION, HASPOSTAL_ADD,
    EXPRESSIONPHONE)
VALUES (100, 0, 0, SYSDATE, 0, SYSDATE, 0, 'United States', 'United States of America', 'US', 100, 'Y', 'N', '(000) 000-0000');

INSERT INTO C_COUNTRY (C_COUNTRY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, COUNTRYCODE, C_CURRENCY_ID, HASREGION, HASPOSTAL_ADD,
    EXPRESSIONPHONE)
VALUES (101, 0, 0, SYSDATE, 0, SYSDATE, 0, 'Canada', 'Canada', 'CA', 105, 'Y', 'N', '(000) 000-0000');

INSERT INTO C_COUNTRY (C_COUNTRY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, COUNTRYCODE, C_CURRENCY_ID, HASREGION, HASPOSTAL_ADD,
    EXPRESSIONPHONE)
VALUES (102, 0, 0, SYSDATE, 0, SYSDATE, 0, 'Germany', 'Federal Republic of Germany', 'DE', 102, 'Y', 'N', '00-000000');

INSERT INTO C_COUNTRY (C_COUNTRY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, COUNTRYCODE, C_CURRENCY_ID, HASREGION, HASPOSTAL_ADD,
    EXPRESSIONPHONE)
VALUES (103, 0, 0, SYSDATE, 0, SYSDATE, 0, 'United Kingdom', 'United Kingdom', 'GB', 103, 'N', 'N', '000-00000000');

INSERT INTO C_COUNTRY (C_COUNTRY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, COUNTRYCODE, C_CURRENCY_ID, HASREGION, HASPOSTAL_ADD,
    EXPRESSIONPHONE)
VALUES (104, 0, 0, SYSDATE, 0, SYSDATE, 0, 'Japan', 'Japan', 'JP', 104, 'Y', 'N', '00-0000-0000');

INSERT INTO C_COUNTRY (C_COUNTRY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, COUNTRYCODE, C_CURRENCY_ID, HASREGION, HASPOSTAL_ADD,
    EXPRESSIONPHONE)
VALUES (105, 0, 0, SYSDATE, 0, SYSDATE, 0, 'France', 'French Republic', 'FR', 102, 'N', 'N', '00-00000000');

INSERT INTO C_COUNTRY (C_COUNTRY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, COUNTRYCODE, C_CURRENCY_ID, HASREGION, HASPOSTAL_ADD,
    EXPRESSIONPHONE)
VALUES (106, 0, 0, SYSDATE, 0, SYSDATE, 0, 'Spain', 'Kingdom of Spain', 'ES', 102, 'Y', 'N', '000-000000');

INSERT INTO C_COUNTRY (C_COUNTRY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, COUNTRYCODE, C_CURRENCY_ID, HASREGION, HASPOSTAL_ADD,
    EXPRESSIONPHONE)
VALUES (107, 0, 0, SYSDATE, 0, SYSDATE, 0, 'Australia', 'Commonwealth of Australia', 'AU', 100, 'Y', 'N', '(00) 0000-0000');

INSERT INTO C_COUNTRY (C_COUNTRY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, COUNTRYCODE, C_CURRENCY_ID, HASREGION, HASPOSTAL_ADD,
    EXPRESSIONPHONE)
VALUES (108, 0, 0, SYSDATE, 0, SYSDATE, 0, 'Mexico', 'United Mexican States', 'MX', 100, 'Y', 'N', '(00) 0000-0000');

INSERT INTO C_COUNTRY (C_COUNTRY_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, COUNTRYCODE, C_CURRENCY_ID, HASREGION, HASPOSTAL_ADD,
    EXPRESSIONPHONE)
VALUES (109, 0, 0, SYSDATE, 0, SYSDATE, 0, 'Brazil', 'Federative Republic of Brazil', 'BR', 100, 'Y', 'N', '(00) 0000-0000');

-- ============================================================
-- C_REGION: Regions/States
-- ============================================================
INSERT INTO C_REGION (C_REGION_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, C_COUNTRY_ID)
VALUES (100, 0, 0, SYSDATE, 0, SYSDATE, 0, 'California', 'CA', 100);

INSERT INTO C_REGION (C_REGION_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, C_COUNTRY_ID)
VALUES (101, 0, 0, SYSDATE, 0, SYSDATE, 0, 'New York', 'NY', 100);

INSERT INTO C_REGION (C_REGION_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, C_COUNTRY_ID)
VALUES (102, 0, 0, SYSDATE, 0, SYSDATE, 0, 'Ontario', 'ON', 101);

INSERT INTO C_REGION (C_REGION_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, C_COUNTRY_ID)
VALUES (103, 0, 0, SYSDATE, 0, SYSDATE, 0, 'Bavaria', 'BY', 102);

INSERT INTO C_REGION (C_REGION_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, NAME, DESCRIPTION, C_COUNTRY_ID)
VALUES (104, 0, 0, SYSDATE, 0, SYSDATE, 0, 'Tokyo', 'TK', 104);

-- ============================================================
-- C_BPARTNER: Business partners (customers/vendors)
-- ============================================================
INSERT INTO C_BPARTNER (C_BPARTNER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, ISCUSTOMER, ISVENDOR, ISEMPLOYEE, ISSALESREP)
VALUES (100, 11, 11, SYSDATE, 100, SYSDATE, 100, 'SEED', 'Seed Farm Inc', 'Y', 'Y', 'N', 'N');

INSERT INTO C_BPARTNER (C_BPARTNER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, ISCUSTOMER, ISVENDOR, ISEMPLOYEE, ISSALESREP)
VALUES (101, 11, 11, SYSDATE, 100, SYSDATE, 100, 'TREE', 'TreeLine Nursery', 'Y', 'N', 'N', 'N');

INSERT INTO C_BPARTNER (C_BPARTNER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, ISCUSTOMER, ISVENDOR, ISEMPLOYEE, ISSALESREP)
VALUES (102, 11, 11, SYSDATE, 100, SYSDATE, 100, 'FERT', 'Fertilizer World', 'N', 'Y', 'N', 'N');

INSERT INTO C_BPARTNER (C_BPARTNER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, ISCUSTOMER, ISVENDOR, ISEMPLOYEE, ISSALESREP)
VALUES (103, 11, 11, SYSDATE, 100, SYSDATE, 100, 'PATIO', 'Patio Designs LLC', 'Y', 'N', 'N', 'N');

INSERT INTO C_BPARTNER (C_BPARTNER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, ISCUSTOMER, ISVENDOR, ISEMPLOYEE, ISSALESREP)
VALUES (104, 11, 11, SYSDATE, 100, SYSDATE, 100, 'LAWN', 'LawnCare Supplies', 'N', 'Y', 'N', 'N');

INSERT INTO C_BPARTNER (C_BPARTNER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, ISCUSTOMER, ISVENDOR, ISEMPLOYEE, ISSALESREP)
VALUES (105, 11, 11, SYSDATE, 100, SYSDATE, 100, 'BLOOM', 'Bloom & Grow Co', 'Y', 'Y', 'N', 'N');

INSERT INTO C_BPARTNER (C_BPARTNER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, ISCUSTOMER, ISVENDOR, ISEMPLOYEE, ISSALESREP)
VALUES (106, 11, 11, SYSDATE, 100, SYSDATE, 100, 'GREEN', 'GreenThumb Gardens', 'Y', 'N', 'N', 'N');

INSERT INTO C_BPARTNER (C_BPARTNER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, ISCUSTOMER, ISVENDOR, ISEMPLOYEE, ISSALESREP)
VALUES (107, 11, 11, SYSDATE, 100, SYSDATE, 100, 'SOIL', 'Soil Masters', 'N', 'Y', 'N', 'N');

INSERT INTO C_BPARTNER (C_BPARTNER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, ISCUSTOMER, ISVENDOR, ISEMPLOYEE, ISSALESREP)
VALUES (108, 11, 11, SYSDATE, 100, SYSDATE, 100, 'ROSE', 'Rose Valley Florist', 'Y', 'N', 'N', 'N');

INSERT INTO C_BPARTNER (C_BPARTNER_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, ISCUSTOMER, ISVENDOR, ISEMPLOYEE, ISSALESREP)
VALUES (109, 11, 12, SYSDATE, 100, SYSDATE, 100, 'HARVEST', 'Harvest Tools Co', 'N', 'Y', 'N', 'N');

-- ============================================================
-- M_PRODUCT: Products
-- ============================================================
INSERT INTO M_PRODUCT (M_PRODUCT_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, PRODUCTTYPE, C_UOM_ID)
VALUES (100, 11, 11, SYSDATE, 100, SYSDATE, 100, 'ROSE-RED', 'Red Rose Bush', 'I', 100);

INSERT INTO M_PRODUCT (M_PRODUCT_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, PRODUCTTYPE, C_UOM_ID)
VALUES (101, 11, 11, SYSDATE, 100, SYSDATE, 100, 'TULIP-MIX', 'Tulip Bulb Mix (50)', 'I', 100);

INSERT INTO M_PRODUCT (M_PRODUCT_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, PRODUCTTYPE, C_UOM_ID)
VALUES (102, 11, 11, SYSDATE, 100, SYSDATE, 100, 'FERT-ORG', 'Organic Fertilizer 25lb', 'I', 100);

INSERT INTO M_PRODUCT (M_PRODUCT_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, PRODUCTTYPE, C_UOM_ID)
VALUES (103, 11, 11, SYSDATE, 100, SYSDATE, 100, 'SOIL-TOP', 'Premium Topsoil 40lb', 'I', 100);

INSERT INTO M_PRODUCT (M_PRODUCT_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, PRODUCTTYPE, C_UOM_ID)
VALUES (104, 11, 11, SYSDATE, 100, SYSDATE, 100, 'SHOVEL-LG', 'Garden Shovel Large', 'I', 100);

INSERT INTO M_PRODUCT (M_PRODUCT_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, PRODUCTTYPE, C_UOM_ID)
VALUES (105, 11, 11, SYSDATE, 100, SYSDATE, 100, 'HOSE-50', 'Garden Hose 50ft', 'I', 100);

INSERT INTO M_PRODUCT (M_PRODUCT_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, PRODUCTTYPE, C_UOM_ID)
VALUES (106, 11, 11, SYSDATE, 100, SYSDATE, 100, 'MULCH-CYP', 'Cypress Mulch 3cu.ft', 'I', 100);

INSERT INTO M_PRODUCT (M_PRODUCT_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, PRODUCTTYPE, C_UOM_ID)
VALUES (107, 11, 11, SYSDATE, 100, SYSDATE, 100, 'PRUNE-KIT', 'Pruning Tool Kit', 'I', 100);

INSERT INTO M_PRODUCT (M_PRODUCT_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, PRODUCTTYPE, C_UOM_ID)
VALUES (108, 11, 11, SYSDATE, 100, SYSDATE, 100, 'LAWN-SEED', 'Lawn Seed Mix 10lb', 'I', 100);

INSERT INTO M_PRODUCT (M_PRODUCT_ID, AD_CLIENT_ID, AD_ORG_ID, CREATED, CREATEDBY,
    UPDATED, UPDATEDBY, VALUE, NAME, PRODUCTTYPE, C_UOM_ID)
VALUES (109, 11, 11, SYSDATE, 100, SYSDATE, 100, 'POT-CLAY', 'Clay Flower Pot 12in', 'I', 100);

COMMIT;
